apiVersion: v1
kind: Pod
metadata:
 name: multi-container
spec:
 containers:
 - name: nginx # by default nginx will run without giving any command
   image: nginx
 - name: sidecar
   image: almalinux:8 # it will come and exited
   # we need to give some command to run almalinux
   command: "sleep 200" # this container will alive for 200 seconds and then it iwll exited