apiVersion: v1
kind: Pod
metadata:
  name: config-pod
spec:
  containers:
  - name: config-pod
    image: nginx
    env: 
    - name: COURSE
      valueFrom:
        configMapkeyRef:
         name: course-config
         value: COURSE
    - name: PERSON
      valueFrom:
        configMapkeyRef:
         name: course-config
         value: TRAINER
    - name: DURATION
      valueFrom:
        configMapkeyRef:
         name: course-config
         value: DURATION